"""init_roster_db

Revision ID: 21a0446b79c9
Revises: 
Create Date: 2026-09-24 13:36:32.127290

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21a0446b79c9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('application_resources',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=25), nullable=False),
    sa.Column('description', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('events_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('level', sa.String(length=10), nullable=False),
    sa.Column('correlation_id', sa.String(length=100), nullable=True),
    sa.Column('happened_at', sa.DateTime(), nullable=False),
    sa.Column('message', sa.String(length=5000), nullable=True),
    sa.Column('traceback', sa.String(length=5000), nullable=True),
    sa.Column('demand_args', sa.String(length=5000), nullable=True),
    sa.Column('application', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('identities',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fname', sa.String(length=50), nullable=True),
    sa.Column('lname', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=75), nullable=False),
    sa.Column('email_verified', sa.Boolean(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('is_activated', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=25), nullable=False),
    sa.Column('description', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('temp_tokens',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('token', sa.String(length=100), nullable=False),
    sa.Column('type', sa.Integer(), nullable=True),
    sa.Column('expired_at', sa.DateTime(), nullable=False),
    sa.Column('json_data', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_temp_tokens_token'), 'temp_tokens', ['token'], unique=True)
    op.create_table('roles_permissions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('resource_id', sa.Integer(), nullable=True),
    sa.Column('mode', sa.String(length=6), nullable=True),
    sa.Column('allow_enumerate', sa.Boolean(), nullable=False),
    sa.Column('allow_read', sa.Boolean(), nullable=False),
    sa.Column('allow_create', sa.Boolean(), nullable=False),
    sa.Column('allow_edit', sa.Boolean(), nullable=False),
    sa.Column('allow_delete', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['resource_id'], ['application_resources.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roles_permissions_resource_id'), 'roles_permissions', ['resource_id'], unique=False)
    op.create_index(op.f('ix_roles_permissions_role_id'), 'roles_permissions', ['role_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('identity_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('pwd', sa.String(length=75), nullable=False),
    sa.Column('email_2fa_enabled', sa.Boolean(), nullable=False),
    sa.Column('deleted_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['identity_id'], ['identities.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_identity_id'), 'users', ['identity_id'], unique=False)
    op.create_index(op.f('ix_users_role_id'), 'users', ['role_id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_role_id'), table_name='users')
    op.drop_index(op.f('ix_users_identity_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_roles_permissions_role_id'), table_name='roles_permissions')
    op.drop_index(op.f('ix_roles_permissions_resource_id'), table_name='roles_permissions')
    op.drop_table('roles_permissions')
    op.drop_index(op.f('ix_temp_tokens_token'), table_name='temp_tokens')
    op.drop_table('temp_tokens')
    op.drop_table('roles')
    op.drop_table('identities')
    op.drop_table('events_log')
    op.drop_table('application_resources')
    # ### end Alembic commands ###
