[build-system]
requires = ["setuptools>=82.0"]
build-backend = "setuptools.build_meta"


[project]
name = "repo_sqlalchemy"
version = "0.1.0"
description = 'package contains defenitions implementation of data access layer with SQLAlchemy lib.'
dependencies = [
    'core_contracts == 0.1.0',
    'SQLAlchemy == 2.0.49',
    'psycopg2 == 2.9.12'
]
