"""
Django settings for setup project.

Generated by 'django-admin startproject' using Django 6.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

import sys
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(BASE_DIR / 'src'))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

VALKEY_URL = "valkey://localhost:6379"

RABBITMQ = {
    'HOST': 'localhost',
    'USERNAME': 'guest',
    'PASSWORD': 'guest',
    
    'EXCHANGES': {
        'LOGGING': 'pizza:logging',
        'AUTH_2FA_EMAILER': 'verification:2fa:email'
    }
}

DATABASES = {
    'default': {},
    'PIZZA_APP': {
        'ENV1': 'postgresql+psycopg2://username:password@host/dbname'
    }
}

SECURITY_AUTH = {
    'SECRET_JWT_KEY': 'AWDJy-DOlkeVBZ80P-1vD6oY9QSpiJv3XOkRwSiqSA8',
    'JWT_ALGORITHM': 'HS256',
    'ACCESS_TOKEN_SECONDS_TTL': 6000,
    'REFRESH_TOKEN_SECONDS_TTL': 9000
}

SECURITY_AUTH_2FA = {
    'DEFAULT_EMAIL_2FA_ENABLED': True,
    'EMAIL_CODE_SECONDS_TTL': 300,
    'EMAIL_REGEX_TEMPLATE': '[^@]+@[^@]+', #[^@]+@[^@]+\.[^@]+
}

SIGNUP_DEFAULT_ROLE_ID = 4

ALLOWED_HOSTS = []


# Application definition
INSTALLED_APPS = [
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.messages',

    # Third-party apps
    'rest_framework',
    
    # Local apps (Reference the Config class directly)
    'src.api_core.apps.ApiCoreConfig',
    'src.pizza.apps.PizzaConfig',
    'src.permission.apps.PermissionConfig',
    'src.identity.apps.IdentityConfig',
    'src.auth.apps.AuthConfig',    
]

MIDDLEWARE = [
    'src.api_core.middleware.AuthorizationMiddleware'
]

ROOT_URLCONF = 'src.setup.urls'

WSGI_APPLICATION = 'src.setup.wsgi.application'

TEMPLATES = []

REST_FRAMEWORK = {
    'DEFAULT_RENDERER_CLASSES': [
        'src.api_core.renderers.CustomBrowsableAPIRenderer',
        'rest_framework.renderers.JSONRenderer',
    ],
    'EXCEPTION_HANDLER':'src.api_core.utils.api_internal_exception_handler',

    'DEFAULT_PERMISSION_CLASSES': (),
    'DEFAULT_AUTHENTICATION_CLASSES': (),
}

if DEBUG:

    INSTALLED_APPS.append('django.contrib.staticfiles')

    MIDDLEWARE = [
            'django.contrib.sessions.middleware.SessionMiddleware',
        ] + MIDDLEWARE

    TEMPLATES.append(
        {
            'BACKEND': 'django.template.backends.django.DjangoTemplates',
            'DIRS': [str(BASE_DIR / 'templates')],
            'APP_DIRS': True,
            'OPTIONS': {
                'context_processors': [
                    'django.template.context_processors.request',
                    'django.contrib.messages.context_processors.messages',
                ],
            }
        }
    )


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = []

# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'

